from django.urls import path, re_path

from . import views

urlpatterns = [
    path(
        '',
        views.index,
        name='index'
    ),
    path(
        'books/',
        views.BookListView.as_view(),
        name='books'
    ),
    re_path(
        r'^book/(?P<pk>\d+)$',
        views.BookDetailView.as_view(),
        name='book_detail'
    ),
    path(
        'authors/',
        views.AuthorListView.as_view(),
        name='authors'
    ),
    re_path(
        r'^author/(?P<pk>\d+)$',
        views.AuthorDetailView.as_view(),
        name='author_detail'
    ),
    path(
        r'^mybooks/$',
        views.LoanedBooksByUserListView.as_view(),
        name='my_borrowed'
    ),
    path(
        'borrowed/',
        views.LoanedBooksListView.as_view(),
        name='borrowed'
    ),
    path(
        'book/<uuid:pk>/renew',
        views.RenewBookLibrarian,
        name='book_renew_librarian'
    ),
    path(
        'author/create',
        views.AuthorCreate.as_view(),
        name='author_create'
    ),
    path(
        'author/<int:pk>/update',
        views.AuthorUpdate.as_view(),
        name='author_update'
    ),
    path(
        'author/<int:pk>/delete',
        views.AuthorDelete.as_view(),
        name='author_delete'
    ),
    path(
        'book/create',
        views.BookCreate.as_view(),
        name='book_create'
    ),
    path(
        'book/<int:pk>/update',
        views.BookUpdate.as_view(),
        name='book_update'
    ),
    path(
        'book/<int:pk>/delete',
        views.BookDelete.as_view(),
        name='book_delete'
    ),
]
