# Generated by Django 5.2.8 on 2026-05-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Отметить как возвращенную'),)},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('f', 'На реставрации'), ('l', 'На руках'), ('a', 'В наличии'), ('r', 'Забронирована')], default='a', help_text='Метка наличия', max_length=1),
        ),
    ]
